### ISSUE TITLE
Esse app fica igual ao site

### ISSUE THREAD

**Issue by joliviere** [mannoeu/MooveTV#3]
Esse app fica com a mesma aparência do [Anime TV](https://animetv.biz) ?

**Comment by mannoeu** [comment]
> Esse app fica com a mesma aparência do [Anime TV](https://animetv.biz) ?

Olá, não entendi muito bem sua pergunta.

Infelizmente o MooveTV não está funcionando, pois a API que disponibilizava os animes acabou sofrendo alterações e adicionando autenticação e criptografia. :/

**Comment by mannoeu** [comment]
⚠️ Atualização:
A api voltou a funcionar
